/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { MedicService } from "../medic.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MedicCreateInput } from "./MedicCreateInput";
import { Medic } from "./Medic";
import { MedicFindManyArgs } from "./MedicFindManyArgs";
import { MedicWhereUniqueInput } from "./MedicWhereUniqueInput";
import { MedicUpdateInput } from "./MedicUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class MedicControllerBase {
  constructor(
    protected readonly service: MedicService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Medic })
  @nestAccessControl.UseRoles({
    resource: "Medic",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createMedic(@common.Body() data: MedicCreateInput): Promise<Medic> {
    return await this.service.createMedic({
      data: data,
      select: {
        createdAt: true,
        id: true,
        medic_email: true,
        medic_last_name: true,
        medic_name: true,
        medic_password: true,
        medic_rut: true,
        medic_specialty: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Medic] })
  @ApiNestedQuery(MedicFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Medic",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async medics(@common.Req() request: Request): Promise<Medic[]> {
    const args = plainToClass(MedicFindManyArgs, request.query);
    return this.service.medics({
      ...args,
      select: {
        createdAt: true,
        id: true,
        medic_email: true,
        medic_last_name: true,
        medic_name: true,
        medic_password: true,
        medic_rut: true,
        medic_specialty: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Medic })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Medic",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async medic(
    @common.Param() params: MedicWhereUniqueInput
  ): Promise<Medic | null> {
    const result = await this.service.medic({
      where: params,
      select: {
        createdAt: true,
        id: true,
        medic_email: true,
        medic_last_name: true,
        medic_name: true,
        medic_password: true,
        medic_rut: true,
        medic_specialty: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Medic })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Medic",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateMedic(
    @common.Param() params: MedicWhereUniqueInput,
    @common.Body() data: MedicUpdateInput
  ): Promise<Medic | null> {
    try {
      return await this.service.updateMedic({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          medic_email: true,
          medic_last_name: true,
          medic_name: true,
          medic_password: true,
          medic_rut: true,
          medic_specialty: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Medic })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Medic",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteMedic(
    @common.Param() params: MedicWhereUniqueInput
  ): Promise<Medic | null> {
    try {
      return await this.service.deleteMedic({
        where: params,
        select: {
          createdAt: true,
          id: true,
          medic_email: true,
          medic_last_name: true,
          medic_name: true,
          medic_password: true,
          medic_rut: true,
          medic_specialty: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
